const SellingFastData = [
    {
        id: 1,
        tag: "Shampoo",
        spec: "Long & Strong",
        title: "Curry Leaves, Biotin & Mandarin Sulfate Free Shampoo For Long & Strong Hair - 400ml",
        offer1: "Buy 3 @ 1399",
        offer2: "Buy 4 @ 1799",
        image: "./images/product-slider/pr10.webp",
        rating: 4.5,
        verified: 25,
        price: 585,
        comparePrice: 650
    },
    {
        id: 2,
        tag: "Conditioner",
        spec: "Long & Strong",
        title: "Curry Leaves, Biotin & Mandarin Paraben Free Conditioner For Long & Strong Hair - 400ml",
        offer1: "Buy 3 @ 1399",
        offer2: "Buy 4 @ 1799",
        image: "./images/product-slider/pr20.webp",
        rating: 4.7,
        verified: 36,
        price: 630,
        comparePrice: 700
    },
    {
        id: 3,
        tag: "Body wash",
        spec: "Hydration",
        title: "Coconut Water & Mimosa Sulfate Free Body Wash - 200ml",
        offer1: "Buy 3 @ 1399",
        offer2: "Buy 4 @ 1799",
        image: "./images/product-slider/pr30.webp",
        rating: 5,
        verified: 5,
        price: 195,
        comparePrice: 300
    },
    {
        id: 4,
        tag: "Shampoo",
        spec: "Volume & Bounce",
        title: "Coconut Water & Mimosa Flower Sulfate Free Volume and Bounty Shampoo - 400ml",
        offer1: "Buy 3 @ 1399",
        offer2: "Buy 4 @ 1799",
        image: "./images/product-slider/pr40.webp",
        rating: 4.7,
        verified: 6,
        price: 455,
        comparePrice: 650
    },
    {
        id: 5,
        tag: "Shampoo",
        spec: "Frizz-Free",
        title: "Natural Argan Oil & Lavender Sulfate Free Anti-Frizz Shampoo - 400ml",
        offer1: "Buy 3 @ 1399",
        offer2: "Buy 4 @ 1799",
        image: "./images/product-slider/pr50.webp",
        rating: 4.6,
        verified: 314,
        price: 585,
        comparePrice: 650
    },
    {
        id: 6,
        tag: "Shampoo",
        spec: "Rice Water & Anglica",
        title: "Rice Water & Angelica Seed Oil Silicone Free Shampoo For Curly & Wavy Hair- 400ml",
        offer1: "Buy 3 @ 1399",
        offer2: "Buy 4 @ 1799",
        image: "./images/product-slider/pr60.webp",
        rating: 4.8,
        verified: 54,
        price: 585,
        comparePrice: 650
    },
    {
        id: 7,
        tag: "Conditioner",
        spec: "Frizz-Free",
        title: "Natural Argan Oil & Lavender Paraben Free Anti-Frizz Conditioner - 400ml",
        offer1: "Buy 3 @ 1399",
        offer2: "Buy 4 @ 1799",
        image: "./images/product-slider/pr70.webp",
        rating: 4.5,
        verified: 27,
        price: 630,
        comparePrice: 700
    },
    {
        id: 8,
        tag: "Shampoo",
        spec: "Frizz-Free",
        title: "Argan Oil & Lavender Sulfate Free Anti-Frizz Shampoo - 200ml",
        offer1: "Buy 3 @ 1399",
        offer2: "Buy 4 @ 1799",
        image: "./images/product-slider/pr80.webp",
        rating: 4.6,
        verified: 351,
        price: 315,
        comparePrice: 350
    },
    {
        id: 9,
        tag: "Shampoo",
        spec: "Anti Hairfall",
        title: "Onion, Black Seed & Patchouli Hairfall Control Sulfate Free Shampoo - 200ml",
        offer1: "Buy 3 @ 1399",
        offer2: "Buy 4 @ 1799",
        image: "./images/product-slider/pr90.webp",
        rating: 4.7,
        verified: 189,
        price: 315,
        comparePrice: 350
    },
    {
        id: 10,
        tag: "Shampoo",
        spec: "Anti Hairfall",
        title: "Onion, Blackseed & Patchouli Sulfate Free Shampoo - 400ml",
        offer1: "Buy 3 @ 1399",
        offer2: "Buy 4 @ 1799",
        image: "./images/product-slider/pr100.webp",
        rating: 4.7,
        verified: 120,
        price: 585,
        comparePrice: 650
    },
    {
        id: 11,
        tag: "Shampoo",
        spec: "Colour treated hair",
        title: "Murumuru Butter & Rose Sulfate Free Blooming Color Shampoo - 400ml",
        offer1: "Buy 3 @ 1399",
        offer2: "Buy 4 @ 1799",
        image: "./images/product-slider/pr110.webp",
        rating: 4.4,
        verified: 7,
        price: 585,
        comparePrice: 650
    },
    {
        id: 12,
        tag: "Shampoo",
        spec: "Shine",
        title: "Apple Cider Vinegar & Jasmine Sulfate Free Shampoo - 400ml",
        offer1: "Buy 3 @ 1399",
        offer2: "Buy 4 @ 1799",
        image: "./images/product-slider/pr120.webp",
        rating: 5,
        verified: 4,
        price: 585,
        comparePrice: 650
    },
]

export default SellingFastData;